import test from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { Script } from "node:vm";

const root = new URL("../", import.meta.url);

test("build produces identical single-file HTML from any working directory", () => {
  const abacusBefore = readFileSync(new URL("abacus.html", root), "utf8");
  execFileSync(
    process.execPath,
    [fileURLToPath(new URL("scripts/build.mjs", root))],
    { cwd: "/tmp" },
  );
  const html = readFileSync(new URL("dist/transactions.html", root), "utf8");
  assert.equal(html, readFileSync(new URL("transactions.html", root), "utf8"));
  assert.equal(
    abacusBefore,
    readFileSync(new URL("abacus.html", root), "utf8"),
    "The Transactions build must preserve the independent Abacus file",
  );
  assert.ok(!html.includes("<!-- TRANSACTIONS_SCRIPT -->"));
  assert.ok(!html.includes("<!-- TRANSACTIONS_STYLES -->"));
  const script = html.match(/<script>\n([\s\S]*?)<\/script>/)?.[1];
  assert.ok(script, "The application script must be embedded");
  assert.doesNotThrow(() => new Script(script));
  const externalScripts = [...html.matchAll(/<script[^>]*src="([^"]+)"/g)].map(
    (m) => m[1],
  );
  // SheetJS is no longer loaded with the page; files.js adds it, pinned and
  // hash-checked, only when someone chooses a spreadsheet.
  assert.deepEqual(externalScripts, []);
  assert.ok(
    !/cdnjs|xlsx\.full/.test(html.split("</head>")[0]),
    "no SheetJS in <head>",
  );
  // The fonts are embedded, so the page requests none (ADR 0010).
  assert.ok(!/fonts\.googleapis|fonts\.gstatic|<link\b/.test(html));
  for (const family of ["Frank Ruhl Libre", "Instrument Sans"])
    assert.match(
      html,
      new RegExp(
        `@font-face\\{font-family:"${family}";[^}]*src:url\\(data:font/woff2;base64,`,
      ),
    );
  const template = readFileSync(new URL("index.html", root), "utf8");
  const stripBlocks = (text) =>
    text
      .replace(/<style>[\s\S]*?<\/style>/, "<!-- TRANSACTIONS_STYLES -->")
      .replace(/<script>\n[\s\S]*?<\/script>/, "<!-- TRANSACTIONS_SCRIPT -->")
      .replace(/\n<!-- Generated by npm run build\.[^>]*-->/, "");
  assert.equal(
    stripBlocks(html),
    template,
    "The build must preserve the HTML template",
  );
});
