import test from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { Script } from "node:vm";

const root = new URL("../", import.meta.url);

test("build produces identical single-file HTML from any working directory", () => {
  const abacusBefore = readFileSync(new URL("abacus.html", root), "utf8");
  execFileSync(
    process.execPath,
    [fileURLToPath(new URL("scripts/build.mjs", root))],
    { cwd: "/tmp" },
  );
  const html = readFileSync(new URL("dist/transactions.html", root), "utf8");
  assert.equal(html, readFileSync(new URL("transactions.html", root), "utf8"));
  assert.equal(
    abacusBefore,
    readFileSync(new URL("abacus.html", root), "utf8"),
    "The Transactions build must preserve the independent Abacus file",
  );
  assert.ok(!html.includes("<!-- TRANSACTIONS_SCRIPT -->"));
  assert.ok(!html.includes("<!-- TRANSACTIONS_STYLES -->"));
  const script = html.match(/<script>\n([\s\S]*?)<\/script>/)?.[1];
  assert.ok(script, "The application script must be embedded");
  assert.doesNotThrow(() => new Script(script));
  const externalScripts = [...html.matchAll(/<script[^>]*src="([^"]+)"/g)].map(
    (m) => m[1],
  );
  assert.deepEqual(externalScripts, [
    "https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js",
  ]);
  // The fonts stay on Google Fonts (ADR 0007, the user's decision).
  assert.match(
    html,
    /<link href="https:\/\/fonts\.googleapis\.com\/css2\?family=Frank\+Ruhl\+Libre[^"]*" rel="stylesheet">/,
  );
  const template = readFileSync(new URL("index.html", root), "utf8");
  const stripBlocks = (text) =>
    text
      .replace(/<style>[\s\S]*?<\/style>/, "<!-- TRANSACTIONS_STYLES -->")
      .replace(/<script>\n[\s\S]*?<\/script>/, "<!-- TRANSACTIONS_SCRIPT -->")
      .replace(/\n<!-- Generated by npm run build\.[^>]*-->/, "");
  assert.equal(
    stripBlocks(html),
    template,
    "The build must preserve the HTML template",
  );
});
