import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = fileURLToPath(new URL("../", import.meta.url));
const result = await build({
  absWorkingDir: root,
  entryPoints: ["main.js"],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2022",
  write: false,
  legalComments: "inline",
});
const template = await readFile(path.join(root, "index.html"), "utf8");
const css = await readFile(path.join(root, "styles.css"), "utf8");
const script = result.outputFiles[0].text;
for (const marker of [
  "<!-- TRANSACTIONS_STYLES -->",
  "<!-- TRANSACTIONS_SCRIPT -->",
]) {
  if (template.split(marker).length !== 2)
    throw new Error(`Expected exactly one ${marker}`);
}
// Escape closing tags so program strings cannot terminate an inline block.
const html = template
  .replace(
    "<!doctype html>",
    "<!doctype html>\n<!-- Generated by npm run build. Edit index.html, styles.css and the JavaScript modules. -->",
  )
  .replace(
    "<!-- TRANSACTIONS_STYLES -->",
    () => `<style>\n${css.replace(/<\/style/gi, "<\\/style")}</style>`,
  )
  .replace(
    "<!-- TRANSACTIONS_SCRIPT -->",
    () => `<script>\n${script.replace(/<\/script/gi, "<\\/script")}</script>`,
  );
await mkdir(path.join(root, "dist"), { recursive: true });
await writeFile(path.join(root, "dist/transactions.html"), html);
await writeFile(path.join(root, "transactions.html"), html);
console.log("Built dist/transactions.html and transactions.html");
